# Generated by Django 5.0.6 on 2026-04-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=10)),
                ("rack_id", models.IntegerField()),
                ("retail_price", models.FloatField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("is_geocoded", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "fuel_stations",
                "indexes": [
                    models.Index(fields=["state"], name="fuel_statio_state_db56e5_idx"),
                    models.Index(
                        fields=["retail_price"], name="fuel_statio_retail__463e8c_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="fuel_statio_latitud_c84538_idx",
                    ),
                ],
            },
        ),
    ]
